### ISSUE TITLE
Would the Dataset (aka DataLoader) class be provided?

### ISSUE THREAD

**Issue by ouovowo** [yyssl88/BClean#1]
When i tried to reproduce the result of BClean, i found that the dataset class doesn't exist in the repo. Would it be provided someday?

**Comment by yyssl88** [comment]
Hi ouovowo, 

I apologize for not checking my notifications over the past few months. The current repository is temporary. Please refer to the following link for the complete source code of BClean along with a README.

https://github.com/thethe-github/BClean

Thanks!.
